version: '3.7'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  worker:
    build: .
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
